### ISSUE TITLE
Use the CNM Code of Student Conduct

### ISSUE THREAD

**Issue by deepdivedylan** [deepdivedan/codeathon2018#2]
I took the liberty of referencing the [CNM Student Code of Conduct](https://www.cnm.edu/depts/dean-of-students/student-code-of-conduct) as per commit [e304c8e](https://github.com/deepdivedan/codeathon2018/commit/e304c8e6a6c60cb289f91956eac00cee2eead1e2). I am personally in favor of this, but is this what we, as team, want? I'm creating this issue to facilitate discussion before the rules are fully finalized.

Discuss! 😺

**Comment by decodomain** [comment]
I'm also in favor - I think it may be more than what we need (esp the academic part), but definitely includes all the vital expectations we want to lay out.

**Comment by noeldevelops** [comment]
I'm also in favor - I think it may be more than what we need (esp the academic part), but definitely includes all the vital expectations we want to lay out.
